### ISSUE TITLE
Generalize to N disks?

### ISSUE THREAD

**Issue by boyanpenkov** [andreasscherbaum/uefi-copy-with-grub#2]
Hello Andreas,

I'm following your install notes here -- https://andreas.scherbaum.la/post/2024-07-22_install-debian-bookworm-on-a-software-raid-and-efi/ -- do you think it would be safe to generalize this to multiple disks?

Cheers!

**Comment by andreasscherbaum** [comment]
One way to do this is by making `$device_second` a list of devices, and then loop over the list.

I don't have a test environment for this though.

**Comment by boyanpenkov** [comment]
Super -- thanks kindly for your note.  I found your writeup to be the best, but in the end needed to get this machine up kinda fast, and so gave up on EFI.  I'm booting it off of BIOS, and then have it directly to BTRFS.

I'll have to give learning EFI stuff another shot in the future.

**Comment by andreasscherbaum** [comment]
Thanks!
